"""Hand-curated calibration pairs used to choose the cognate threshold.

Nothing downstream is trustworthy unless we can show the scorer separates
known cognates from known non-cognates. These pairs are drawn from standard
Ibero-Romance historical phonology and etymological dictionaries.

TRUE_COGNATES deliberately over-samples pairs that are *orthographically far
apart* -- that is exactly the population a naive edit distance gets wrong.

NON_COGNATES are pairs where Spanish and Portuguese use etymologically
unrelated words for the same concept.
"""

# (spanish, portuguese, latin-or-source etymon, note)
TRUE_COGNATES: list[tuple[str, str, str]] = [
    ("hijo", "filho", "FILIUM"),
    ("hija", "filha", "FILIAM"),
    ("hablar", "falar", "FABULARE"),
    ("hacer", "fazer", "FACERE"),
    ("harina", "farinha", "FARINAM"),
    ("hierro", "ferro", "FERRUM"),
    ("horno", "forno", "FURNUM"),
    ("hoja", "folha", "FOLIAM"),
    ("hormiga", "formiga", "FORMICAM"),
    ("humo", "fumo", "FUMUM"),
    ("llave", "chave", "CLAVEM"),
    ("llamar", "chamar", "CLAMARE"),
    ("lluvia", "chuva", "PLUVIAM"),
    ("llegar", "chegar", "PLICARE"),
    ("lleno", "cheio", "PLENUM"),
    ("llorar", "chorar", "PLORARE"),
    ("llano", "chao", "PLANUM"),
    ("noche", "noite", "NOCTEM"),
    ("ocho", "oito", "OCTO"),
    ("leche", "leite", "LACTEM"),
    ("hecho", "feito", "FACTUM"),
    ("dicho", "dito", "DICTUM"),
    ("mucho", "muito", "MULTUM"),
    ("pecho", "peito", "PECTUS"),
    ("derecho", "direito", "DIRECTUM"),
    ("ojo", "olho", "OCULUM"),
    ("oreja", "orelha", "AURICULAM"),
    ("viejo", "velho", "VETULUM"),
    ("mujer", "mulher", "MULIEREM"),
    ("trabajo", "trabalho", "TRIPALIUM"),
    ("consejo", "conselho", "CONSILIUM"),
    ("tierra", "terra", "TERRAM"),
    ("piedra", "pedra", "PETRAM"),
    ("fiesta", "festa", "FESTAM"),
    ("siempre", "sempre", "SEMPER"),
    ("cielo", "ceu", "CAELUM"),
    ("fuego", "fogo", "FOCUM"),
    ("puerta", "porta", "PORTAM"),
    ("muerte", "morte", "MORTEM"),
    ("bueno", "bom", "BONUM"),
    ("cuerpo", "corpo", "CORPUS"),
    ("fuerte", "forte", "FORTEM"),
    ("nuevo", "novo", "NOVUM"),
    ("ano", "ano", "ANNUM"),
    ("senor", "senhor", "SENIOREM"),
    ("manana", "manha", "MANEANA"),
    ("mano", "mao", "MANUM"),
    ("pan", "pao", "PANEM"),
    ("corazon", "coracao", "COR"),
    ("leon", "leao", "LEONEM"),
    ("luna", "lua", "LUNAM"),
    ("dolor", "dor", "DOLOREM"),
    ("color", "cor", "COLOREM"),
    ("salir", "sair", "SALIRE"),
    ("ciudad", "cidade", "CIVITATEM"),
    ("verdad", "verdade", "VERITATEM"),
    ("cancion", "cancao", "CANTIONEM"),
    ("agua", "agua", "AQUAM"),
    ("caballo", "cavalo", "CABALLUM"),
    ("libro", "livro", "LIBRUM"),
    ("escribir", "escrever", "SCRIBERE"),
    ("cabeza", "cabeca", "CAPITIAM"),
    ("brazo", "braco", "BRACCHIUM"),
    ("plaza", "praca", "PLATEAM"),
    ("blanco", "branco", "BLANK-"),
    ("hambre", "fome", "FAMINEM"),
    ("azucar", "acucar", "Ar. al-sukkar"),
    ("aceite", "azeite", "Ar. az-zayt"),
    ("aceituna", "azeitona", "Ar. az-zaytuna"),
    ("almohada", "almofada", "Ar. al-mihadda"),
    ("ojala", "oxala", "Ar. law sa- llah"),
    ("zumo", "sumo", "Ar. zum"),
    ("conejo", "coelho", "CUNICULUM"),
    ("pequeno", "pequeno", "pre-Roman"),
    ("hueso", "osso", "OSSUM"),
    ("almuerzo", "almoco", "ADMORDIUM"),
]

NON_COGNATES: list[tuple[str, str, str]] = [
    ("ventana", "janela", "VENTUM vs IANUAM"),
    ("olvidar", "esquecer", "OBLITARE vs EXCADESCERE"),
    ("perro", "cao", "obscure vs CANEM"),
    ("rodilla", "joelho", "ROTELLAM vs GENUCULUM"),
    ("calle", "rua", "CALLEM vs RUGAM"),
    ("cena", "jantar", "CENAM vs IENTACULUM"),
    ("te", "cha", "Min Nan te vs Cantonese cha"),
    ("pina", "abacaxi", "PINEAM vs Tupi"),
    ("maiz", "milho", "Taino vs MILIUM"),
    ("alfombra", "tapete", "Ar. al-hanbal vs TAPETEM"),
    ("albanil", "pedreiro", "Ar. banna vs PETRAM"),
    ("acera", "passeio", "distinct etyma"),
    ("basura", "lixo", "distinct etyma"),
    ("tenedor", "garfo", "distinct etyma"),
    ("postre", "sobremesa", "distinct etyma"),
    ("melocoton", "pessego", "distinct etyma"),
    ("gafas", "oculos", "distinct etyma"),
    ("nino", "crianca", "distinct etyma"),
    ("rojo", "vermelho", "RUSSEUM vs VERMICULUM"),
    ("carretera", "estrada", "distinct etyma"),
    ("enfadado", "zangado", "distinct etyma"),
    ("bolsillo", "algibeira", "ROMANCE vs Ar. al-jayb"),
    ("boligrafo", "caneta", "distinct etyma"),
    ("ordenador", "computador", "distinct etyma"),
]
